[package]
name = "luhtwin"
version = "0.1.0"
authors = ["cali zoots <calizoots@gmail.com>"]
edition = "2021"
description = "A beta horrible Rust error handling library with AnyError and context macros"
license = "GPL-3.0-or-later"
license-file = "LICENSE"
repository = "https://github.com/calizoots/luhtwin"

[dependencies]
